CS_SKINS_ASP/CS_SKINS_ASP/Models/Crate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CS_SKINS_ASP.Models
{
    public class Crate
    {
        public int ID { get; set; }
        [Display(ResourceType = typeof(CS_SKINS_ASP.Views.Crates.ResourceCrate), Name = "Nom")]
        public string Nom { get; set; }
        [Display(ResourceType = typeof(CS_SKINS_ASP.Views.Crates.ResourceCrate), Name = "Prix")]
        public float Prix { get; set; }
        public ICollection<Skins> Skins { get; set; }
        public string ImageNom { get; set; }
        public string ImageType { get; set; }
        public int ImageTaille { get; set; }
        public byte[] ImageData { get; set; }
        [NotMapped]
        public HttpPostedFileBase Fichier { get; set; }
    }
}

CS_SKINS_ASP/CS_SKINS_ASP/Controllers/CratesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CS_SKINS_ASP.Models;
using System.IO;

namespace CS_SKINS_ASP.Controllers
{
    public class CratesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Crates
        public ActionResult Index()
        {
            return View(db.Crates.ToList());
        }

        // GET: Crates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crate crate = db.Crates.Find(id);
            if (crate == null)
            {
                return HttpNotFound();
            }
            return View(crate);
        }

        // GET: Crates/Create
        [Authorize(Roles = "Administrateur")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Crates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nom,Prix,Fichier")] Crate crate)
        {
            if (ModelState.IsValid)
            {
                crate.ImageNom = Path.GetFileName(crate.Fichier.FileName);
                crate.ImageTaille = crate.Fichier.ContentLength;
                crate.ImageType = crate.Fichier.ContentType;
                crate.ImageData = new byte[crate.ImageTaille];
                crate.Fichier.InputStream.Read(crate.ImageData, 0, crate.ImageTaille);
                db.Crates.Add(crate);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(crate);
        }

        // GET: Crates/Edit/5
        [Authorize(Roles = "Administrateur")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crate crate = db.Crates.Find(id);
            if (crate == null)
            {
                return HttpNotFound();
            }
            return View(crate);
        }

        // POST: Crates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nom,Prix,ImageNom,ImageType,ImageTaille,ImageData")] Crate crate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(crate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(crate);
        }

        // GET: Crates/Delete/5
        [Authorize(Roles = "Administrateur")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crate crate = db.Crates.Find(id);
            if (crate == null)
            {
                return HttpNotFound();
            }
            return View(crate);
        }

        // POST: Crates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Crate crate = db.Crates.Find(id);
            db.Crates.Remove(crate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS_SKINS_ASP/CS_SKINS_ASP/Controllers/SkinsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CS_SKINS_ASP.Models;
using System.IO;

namespace CS_SKINS_ASP.Controllers
{
    public class SkinsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Skins
        public ActionResult Index(int? id)
        {
                HttpCookie cookie = new HttpCookie("cookie_skins");
                cookie.Value = id.ToString();
                HttpContext.Response.Cookies.Remove("cookie_skins");
                HttpContext.Response.SetCookie(cookie);

            return View(db.Skins.Where(c=> c.CrateId == id).ToList());
        }

        // GET: Skins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skins skins = db.Skins.Find(id);
            if (skins == null)
            {
                return HttpNotFound();
            }
            return View(skins);
        }

        // GET: Skins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Skins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CrateId,Prix,Probabilité,Rang,Fichier")] Skins skins)
        {
            if (ModelState.IsValid)
            {
                skins.ImageNom = Path.GetFileName(skins.Fichier.FileName);
                skins.ImageTaille = skins.Fichier.ContentLength;
                skins.ImageType = skins.Fichier.ContentType;
                skins.ImageData = new byte[skins.ImageTaille];
                skins.Fichier.InputStream.Read(skins.ImageData, 0, skins.ImageTaille);
                int cookieId = Convert.ToInt32(HttpContext.Request.Cookies.Get("cookie_skins").Value);
                skins.CrateId = cookieId;
                db.Skins.Add(skins);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(skins);
        }

        // GET: Skins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skins skins = db.Skins.Find(id);
            if (skins == null)
            {
                return HttpNotFound();
            }
            return View(skins);
        }

        // POST: Skins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Prix,Probabilité,Rang")] Skins skins)
        {
            if (ModelState.IsValid)
            {
                db.Entry(skins).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(skins);
        }

        // GET: Skins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skins skins = db.Skins.Find(id);
            if (skins == null)
            {
                return HttpNotFound();
            }
            return View(skins);
        }

        // POST: Skins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Skins skins = db.Skins.Find(id);
            db.Skins.Remove(skins);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS_SKINS_ASP/CS_SKINS_ASP/Views/Crates/Create.cshtml
@model CS_SKINS_ASP.Models.Crate

@{
    ViewBag.Title = CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.CreerSujet;
}
<div class="couche textfont">
    <h2>Create</h2>

    @using (Html.BeginForm("Create", "Crates", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Crate</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Fichier, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Fichier, new { type = "file" })
                    @Html.ValidationMessageFor(model => model.Fichier, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Crates/Delete.cshtml
@model CS_SKINS_ASP.Models.Crate

@{
    ViewBag.Title = CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Delete;
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Crate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt>
            Boite: 
        </dt>

        <dd>
            @{
                string src = "";
                src = "data:" + Model.ImageType + ";base64," + Convert.ToBase64String(Model.ImageData);
                <img src="@src" alt="@Model.ImageNom" height="70" width="50" />
            }
        </dd>



    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Crates/Details.cshtml
@model CS_SKINS_ASP.Models.Crate

@{
    ViewBag.Title = CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Details;
}

<div class="couche textfont">
    <h2>Details</h2>

    <div>
        <h4>Crate</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Prix)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prix)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageNom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageNom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageTaille)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageTaille)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageData)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Crates/Edit.cshtml
@model CS_SKINS_ASP.Models.Crate

@{
    ViewBag.Title = CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Edit;
}

<div class="couche textfont">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Crate</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageNom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageNom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageNom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageTaille, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageTaille, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageTaille, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageData, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageData, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageData, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Crates/Index.cshtml
@model IEnumerable<CS_SKINS_ASP.Models.Crate>

@{
    ViewBag.Title = "Index";
}

<div class="couche textfont">
    <h2>Index</h2>

    @if (User.IsInRole("Administrateur"))
    {
        <p>
            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.CreerSujet, "Create")
        </p>
    }
    <table class="table">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{
                        string src = "";
                        src = "data:" + item.ImageType + ";base64," + Convert.ToBase64String(item.ImageData);
                        <img src="@src" alt="@item.ImageNom" height="125" width="125" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prix)
                </td>
                <td>
                    @if (User.IsInRole("Administrateur"))
                {
                        <p>
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Edit, "Edit", new { id = item.ID }) |
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Details, "Details", new { id = item.ID }) |
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Delete, "Delete", new { id = item.ID })
                        </p>
                    }
                    @Html.ActionLink(CS_SKINS_ASP.Views.Crates.ResourceCrate.VoirSkins, "Index", "Skins", new { id = item.ID }, new { id = item.ID })
                </td>
            </tr>
                        }

    </table>
</div>