CS_SKINS_ASP/CS_SKINS_ASP/Models/Ventes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CS_SKINS_ASP.Models
{
    public class Ventes
    {
        public string ImageNom { get; set; }
        public string ImageType { get; set; }
        public int ImageTaille { get; set; }
        public byte[] ImageData { get; set; }
        [NotMapped]
        public HttpPostedFileBase Fichier { get; set; }
        public string NomSkin { get; set; }
        public int ID { get; set; }
        [Display(ResourceType = typeof(CS_SKINS_ASP.Views.Skins.ResourceSkin), Name = "Prix")]
        public float Prix { get; set; }
        public string ContactInfo { get; set; }
        public bool Vendu { get; set; }
        
    }
}

CS_SKINS_ASP/CS_SKINS_ASP/Controllers/VentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CS_SKINS_ASP.Models;
using System.IO;

namespace CS_SKINS_ASP.Controllers
{
    public class VentesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Ventes
        public ActionResult Index()
        {
            return View(db.Ventes.ToList());
        }

        // GET: Ventes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventes ventes = db.Ventes.Find(id);
            if (ventes == null)
            {
                return HttpNotFound();
            }
            return View(ventes);
        }

        // GET: Ventes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ventes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ImageNom,ImageType,ImageTaille,ImageData,Prix,ContactInfo,Fichier,NomSkin")] Ventes ventes)
        {
            if (ModelState.IsValid)
            {
                ventes.ImageNom = Path.GetFileName(ventes.Fichier.FileName);
                ventes.ImageTaille = ventes.Fichier.ContentLength;
                ventes.ImageType = ventes.Fichier.ContentType;
                ventes.ImageData = new byte[ventes.ImageTaille];
                ventes.Fichier.InputStream.Read(ventes.ImageData, 0, ventes.ImageTaille);

                db.Ventes.Add(ventes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ventes);
        }

        // GET: Ventes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventes ventes = db.Ventes.Find(id);
            if (ventes == null)
            {
                return HttpNotFound();
            }
            return View(ventes);
        }

        // POST: Ventes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ImageNom,ImageType,ImageTaille,ImageData,Prix,ContactInfo")] Ventes ventes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ventes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ventes);
        }

        // GET: Ventes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ventes ventes = db.Ventes.Find(id);
            if (ventes == null)
            {
                return HttpNotFound();
            }
            return View(ventes);
        }

        // POST: Ventes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ventes ventes = db.Ventes.Find(id);
            db.Ventes.Remove(ventes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/Create.cshtml
@model CS_SKINS_ASP.Models.Ventes

@{
    ViewBag.Title = "Create";
}
<div class="couche textfont">
    <h2>Create</h2>


    @using (Html.BeginForm("Create", "Ventes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ventes</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Fichier, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Fichier, new { type = "file" })
                    @Html.ValidationMessageFor(model => model.Fichier, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NomSkin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomSkin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomSkin, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactInfo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactInfo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactInfo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/Delete.cshtml
@model CS_SKINS_ASP.Models.Ventes

@{
    ViewBag.Title = "Delete";
}
<div class="couche textfont">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Ventes</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Prix)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prix)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactInfo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactInfo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NomSkin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NomSkin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Vendu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vendu)
            </dd>

            <dd>
                @{
                    string src = "";
                    src = "data:" + Model.ImageType + ";base64," + Convert.ToBase64String(Model.ImageData);
                    <img src="@src" alt="@Model.ImageNom" height="70" width="50" />
                }
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/Details.cshtml
@model CS_SKINS_ASP.Models.Ventes

@{
    ViewBag.Title = "Details";
}
<div class="couche textfont">
    <h2>Details</h2>

    <div>
        <h4>Ventes</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ImageNom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageNom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageTaille)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageTaille)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageData)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Prix)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prix)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactInfo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactInfo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NomSkin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NomSkin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Vendu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vendu)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/Edit.cshtml
@model CS_SKINS_ASP.Models.Ventes

@{
    ViewBag.Title = "Edit";
}
<div class="couche textfont">
    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ventes</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.ImageNom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageNom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageNom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageTaille, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageTaille, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageTaille, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageData, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageData, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageData, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NomSkin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomSkin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomSkin, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactInfo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactInfo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactInfo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Vendu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vendu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vendu, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/Index.cshtml
@model IEnumerable<CS_SKINS_ASP.Models.Ventes>

@{
    ViewBag.Title = "Index";

    var ajaxParam = new AjaxOptions()
    {
        HttpMethod = "get",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "Liste"
    };
}

<div class="couche textfont" id="Liste">
    <h2>Index</h2>

    <p>
        @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.CreerSujet, "Create")
    </p>

    @Html.Partial("_PartialVentesView", Model)

    
</div>

CS_SKINS_ASP/CS_SKINS_ASP/Views/Ventes/_PartialVentesView.cshtml
@model IEnumerable<CS_SKINS_ASP.Models.Ventes>

@{
    var ajaxParam = new AjaxOptions()
    {
        HttpMethod = "get",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "Liste"
    };
}

<div id="Liste">
    <table class="table">
        <tr>
            <th></th>
            <th>
                @*@Html.ActionLink("Nom", "Index", new { OrdreTri = "Nom" })*@
                @Ajax.ActionLink("Nom", "Index", new { OrdreTri = "Nom" }, ajaxParam)
            </th>
            <th>
                @*@Html.ActionLink("Catégorie", "Index", new { OrdreTri = "Nom" })*@
                @Ajax.ActionLink("Prix", "Index", new { OrdreTri = "Nom" }, ajaxParam)
            </th>
            <th>
                @*@Html.ActionLink("Catégorie", "Index", new { OrdreTri = "Nom" })*@
                @Ajax.ActionLink("ContactInfo", "Index", new { OrdreTri = "Nom" }, ajaxParam)
            </th>
            <th>
                @*@Html.ActionLink("Catégorie", "Index", new { OrdreTri = "Nom" })*@
                @Ajax.ActionLink("Vendu", "Index", new { OrdreTri = "Nom" }, ajaxParam)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{
                        string src = "";
                        src = "data:" + item.ImageType + ";base64," + Convert.ToBase64String(item.ImageData);
                        <img src="@src" alt="@item.ImageNom" height="125" width="125" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomSkin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prix)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactInfo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vendu)
                </td>
                <td>
                    @if (User.IsInRole("Administrateur"))
                    {
                        <p>
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Edit, "Edit", new { id = item.ID }) |
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Details, "Details", new { id = item.ID }) |
                            @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Delete, "Delete", new { id = item.ID })
                        </p>
                    }
                </td>
            </tr>
                        }

    </table>
</div>
@*<table class="table">
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomSkin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vendu)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    string src = "";
                    src = "data:" + item.ImageType + ";base64," + Convert.ToBase64String(item.ImageData);
                    <img src="@src" alt="@item.ImageNom" height="125" width="125" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomSkin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendu)
            </td>

            <td>
                @if (User.IsInRole("Administrateur"))
                {
                    <p>
                        @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Edit, "Edit", new { id = item.ID }) |
                        @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Details, "Details", new { id = item.ID }) |
                        @Html.ActionLink(CS_SKINS_ASP.Views.ResourcesCommunes.ResourcesCommunes.Delete, "Delete", new { id = item.ID })
                    </p>
                }
            </td>
        </tr>
                    }

</table>*@